const translations={en:{navServices:"Services",navDemo:"Demo",navMethod:"Method",navAbout:"About",navContact:"Contact",diagnosticCta:"Request an assessment",menuLabel:"Open navigation",heroKicker:"Electrical engineering, BMS and supervision",heroTitle:"Smarter buildings, better controlled and more efficient.",heroSubtitle:"Hypervision designs and integrates electrical, BMS and supervision solutions to make buildings clearer, more efficient and easier to operate.",heroDemo:"View demo",do1:"Control",do1t:"Drive technical equipment with clear logic.",do2:"Supervise",do2t:"Visualize statuses, alarms and commands in real time.",do3:"Optimize",do3t:"Reduce drifts and improve energy efficiency.",servicesTitle:"Services",demoEyebrow:"Interactive demo",demoTitle:"Control a building in a few gestures.",demoText:"A clear interface helps monitor and control building equipment quickly.",contactTitle:"Let's discuss your technical project",contactText:"Installation, renovation, BMS, supervision or technical assistance: let's discuss your need."}};
const metaByLanguage={fr:{title:"Hypervision — Électricité, GTB et supervision pour bâtiments intelligents",description:"Hypervision conçoit et intègre des solutions électriques, GTB, supervision et automatisation pour des bâtiments mieux pilotés.",locale:"fr_FR"},en:{title:"Hypervision - Electrical engineering, BMS and supervision",description:"Hypervision designs and integrates electrical, BMS, supervision and automation solutions for better controlled buildings.",locale:"en_US"}};
const translatableElements=document.querySelectorAll("[data-i18n]");const langButtons=document.querySelectorAll(".lang-btn");const navPanel=document.querySelector(".nav-panel");const menuToggle=document.querySelector(".menu-toggle");const yearElement=document.getElementById("year");const revealElements=document.querySelectorAll(".reveal");
translatableElements.forEach((e)=>e.dataset.frText=e.textContent.trim());
const updateMeta=(lang)=>{const m=metaByLanguage[lang]||metaByLanguage.fr;document.title=m.title;document.querySelector('meta[name="description"]').setAttribute("content",m.description);document.querySelector('meta[property="og:title"]').setAttribute("content",m.title);document.querySelector('meta[property="og:description"]').setAttribute("content",m.description);document.querySelector('meta[property="og:locale"]').setAttribute("content",m.locale)};
const applyLanguage=(lang)=>{translatableElements.forEach((e)=>{const key=e.dataset.i18n;const value=lang==="fr"?e.dataset.frText:translations.en[key];if(value)e.textContent=value});document.documentElement.lang=lang;langButtons.forEach((b)=>{const a=b.dataset.lang===lang;b.classList.toggle("is-active",a);b.setAttribute("aria-pressed",String(a))});updateMeta(lang);localStorage.setItem("hypervision-language",lang)};
langButtons.forEach((button)=>button.addEventListener("click",()=>applyLanguage(button.dataset.lang)));
if(menuToggle&&navPanel){menuToggle.addEventListener("click",()=>{const isOpen=navPanel.classList.toggle("is-open");menuToggle.setAttribute("aria-expanded",String(isOpen));});navPanel.querySelectorAll("a").forEach((link)=>link.addEventListener("click",()=>navPanel.classList.remove("is-open")));}
if(yearElement)yearElement.textContent=String(new Date().getFullYear());
if("IntersectionObserver" in window){const observer=new IntersectionObserver((entries)=>entries.forEach((entry)=>{if(entry.isIntersecting){entry.target.classList.add("is-visible");observer.unobserve(entry.target)}}),{threshold:.12});revealElements.forEach((el)=>observer.observe(el));} else revealElements.forEach((el)=>el.classList.add("is-visible"));
const demoState={lights:false,hvac:false,blinds:false,security:false};
const energyValue=document.getElementById("energy-value");const comfortBadge=document.getElementById("comfort-badge");const securityDot=document.getElementById("security-dot");
document.querySelectorAll(".toggle").forEach((button)=>{button.addEventListener("click",()=>{const key=button.dataset.control;demoState[key]=!demoState[key];button.classList.toggle("is-on",demoState[key]);button.setAttribute("aria-pressed",String(demoState[key]));document.body.classList.toggle("lights-on",demoState.lights);document.body.classList.toggle("hvac-on",demoState.hvac);document.body.classList.toggle("blinds-closed",demoState.blinds);document.body.classList.toggle("security-on",demoState.security);if(energyValue)energyValue.textContent=(38.4-(demoState.lights?1.8:0)+(demoState.hvac?2.6:0)+(demoState.security?0.4:0)).toFixed(1);if(comfortBadge)comfortBadge.textContent=demoState.hvac?"Confort renforcé":"Confort normal";if(securityDot)securityDot.textContent=demoState.security?"Mode Présence":"Mode Normal";});});
applyLanguage(localStorage.getItem("hypervision-language")==="en"?"en":"fr");
