import test from 'node:test';
import assert from 'node:assert/strict';
import {defaults,createDraft,totals,issue,issueErrors,validateData,lineTotals,today} from '../admin/core.mjs';
const fixture=()=>{const data=defaults();Object.assign(data.company,{legalName:'Test fixture',form:'EI',address:'Fictional address',siret:'00000000000000',vatMode:'taxable',vatNumber:'FR00000000000',lateRate:'Test rate'});data.clients.push({id:'client-test',kind:'private',name:'Fictional client',address:'Fictional address',email:'',phone:'',siren:'',vatNumber:''});return data;};
function draft(type='quote',brand='hypervision'){const d=createDraft(type,brand);d.clientId='client-test';d.title='Test document';d.schedule='Test schedule';d.lines=[{description:'Fixture line',quantity:2,unit:'u',price:100,discount:10,vat:20}];return d;}
test('VAT and line discounts use cents, including mixed VAT and fractional quantities',()=>{const data=fixture(),d=draft();d.lines.push({description:'Other',quantity:1.5,unit:'h',price:10.01,discount:0,vat:5.5});assert.deepEqual(totals(d,data.company),{net:19502,tax:3683,total:23185,groups:{20:3600,5.5:83}});data.company.vatMode='exempt';assert.equal(totals(d,data.company).total,19502);assert.equal(totals(d,data.company).tax,0);});
test('invalid values are rejected instead of creating NaN or negative amounts',()=>{for(const change of [{quantity:0},{price:-1},{vat:NaN},{discount:101}])assert.throws(()=>lineTotals({...draft().lines[0],...change}));});
test('final issue blocks missing legal information and keeps draft unnumbered',()=>{const data=defaults(),d=draft();assert.ok(issueErrors(d,data).length>=3);assert.throws(()=>issue(d,data));assert.equal(d.number,'');assert.equal(data.company.nextQuote,1);});
test('quote sequence is shared across brands and invoices cannot be created or issued',()=>{const data=fixture();for(const brand of ['hypervision','atelier']){const d=draft('quote',brand);data.documents.push(d);issue(d,data);}assert.match(data.documents[0].number,/-00001$/);assert.match(data.documents[1].number,/-00002$/);assert.equal(data.company.nextQuote,3);assert.equal(data.company.nextInvoice,1);assert.throws(()=>createDraft('invoice'),/désactivée/);const old={...draft(),type:'invoice'};assert.throws(()=>issue(old,data),/désactivée/);validateData(data);});
test('issued snapshots remain intact after changes to company or client',()=>{const data=fixture(),d=draft();data.documents.push(d);issue(d,data);data.company.legalName='Changed';data.clients[0].name='Changed';assert.equal(d.issuer.legalName,'Test fixture');assert.equal(d.customer.name,'Fictional client');assert.throws(()=>issue(d,data),/déjà/);});
test('backdated emission and duplicate numbering are rejected',()=>{const data=fixture(),first=draft();data.documents.push(first);issue(first,data);const old=draft();old.date='2020-01-01';assert.throws(()=>issue(old,data),/précéder/);data.company.nextQuote=1;assert.throws(()=>issue(draft(),data),/existe déjà/);});
test('backup schema rejects duplicate IDs and corrupted documents',()=>{const data=fixture(),d=draft();data.documents.push(d);validateData(data);data.documents.push(structuredClone(d));assert.throws(()=>validateData(data));assert.throws(()=>validateData({schema:2}));});
