import test from 'node:test';
import assert from 'node:assert/strict';
import {defaults,createDraft,totals,issue,issueErrors,validateData,lineTotals,today} from '../admin/core.mjs';
const fixture=()=>{const data=defaults();Object.assign(data.company,{legalName:'Test fixture',form:'EI',address:'Fictional address',siret:'00000000000000',vatMode:'taxable',vatNumber:'FR00000000000',lateRate:'Test rate'});data.clients.push({id:'client-test',kind:'private',name:'Fictional client',address:'Fictional address',email:'',phone:'',siren:'',vatNumber:''});return data;};
function draft(type='invoice',brand='hypervision'){const d=createDraft(type,brand);d.clientId='client-test';d.title='Test document';d.schedule='Test schedule';d.lines=[{description:'Fixture line',quantity:2,unit:'u',price:100,discount:10,vat:20}];return d;}
test('VAT and line discounts use cents, including mixed VAT and fractional quantities',()=>{const data=fixture(),d=draft();d.lines.push({description:'Other',quantity:1.5,unit:'h',price:10.01,discount:0,vat:5.5});assert.deepEqual(totals(d,data.company),{net:19502,tax:3683,total:23185,groups:{20:3600,5.5:83}});data.company.vatMode='exempt';assert.equal(totals(d,data.company).total,19502);assert.equal(totals(d,data.company).tax,0);});
test('invalid values are rejected instead of creating NaN or negative invoices',()=>{for(const change of [{quantity:0},{price:-1},{vat:NaN},{discount:101}])assert.throws(()=>lineTotals({...draft().lines[0],...change}));});
test('final issue blocks missing legal information and keeps draft unnumbered',()=>{const data=defaults(),d=draft();assert.ok(issueErrors(d,data).length>=3);assert.throws(()=>issue(d,data));assert.equal(d.number,'');assert.equal(data.company.nextInvoice,1);});
test('invoice sequence is shared across brands and separate from quotes',()=>{const data=fixture();for(const brand of ['hypervision','atelier']){const d=draft('invoice',brand);data.documents.push(d);issue(d,data);}const q=draft('quote');data.documents.push(q);issue(q,data);assert.match(data.documents[0].number,/-00001$/);assert.match(data.documents[1].number,/-00002$/);assert.match(q.number,/^DEV-\d{4}-00001$/);assert.equal(data.company.nextInvoice,3);assert.equal(data.company.nextQuote,2);validateData(data);});
test('issued snapshots remain intact after changes to company or client',()=>{const data=fixture(),d=draft();data.documents.push(d);issue(d,data);data.company.legalName='Changed';data.clients[0].name='Changed';assert.equal(d.issuer.legalName,'Test fixture');assert.equal(d.customer.name,'Fictional client');assert.throws(()=>issue(d,data),/déjà/);});
test('backdated emission and duplicate numbering are rejected',()=>{const data=fixture(),first=draft();data.documents.push(first);issue(first,data);const old=draft();old.date='2020-01-01';assert.throws(()=>issue(old,data),/précéder/);data.company.nextInvoice=1;assert.throws(()=>issue(draft(),data),/existe déjà/);});
test('backup schema rejects duplicate IDs and corrupted documents',()=>{const data=fixture(),d=draft();data.documents.push(d);validateData(data);data.documents.push(structuredClone(d));assert.throws(()=>validateData(data));assert.throws(()=>validateData({schema:2}));});
test('vault rejects wrong credentials, encrypts storage, restores backups and detects concurrent writes',async()=>{
  const store=new Map();globalThis.localStorage={getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)};
  const vault=await import('../admin/vault.mjs');
  // The initializer is verified in the browser. Isolated vault tests use an independently generated envelope.
  const enc=new TextEncoder(),password='test-only-passphrase-2026',salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12));
  const material=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:600000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt']);
  const data=fixture();data.revision=1;const b64=x=>Buffer.from(x).toString('base64');const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:enc.encode('hypervision-vault-v1')},key,enc.encode(JSON.stringify(data)));
  localStorage.setItem(vault.storageKey,JSON.stringify({format:'hypervision-vault-v1',iterations:600000,salt:b64(salt),iv:b64(iv),revision:1,ciphertext:b64(ciphertext)}));
  await assert.rejects(vault.unlock('wrong',password));await assert.rejects(vault.unlock('admin','bad-password'));
  const unlocked=await vault.unlock('admin',password);unlocked.company.legalName='Private company test';await vault.save(unlocked);const backup=vault.backup();assert.ok(!backup.includes('Private company test'));assert.ok(!backup.includes(password));
  vault.lock();await assert.rejects(vault.save(unlocked));await assert.rejects(vault.inspectBackup(backup,'bad-password'));const checked=await vault.inspectBackup(backup,password);assert.equal(vault.restore(checked).company.legalName,'Private company test');
  await vault.changePassword(checked.data,password,'new-test-only-passphrase');vault.lock();await assert.rejects(vault.unlock('admin',password));const changed=await vault.unlock('admin','new-test-only-passphrase');assert.equal(changed.company.legalName,'Private company test');
  const conflict=JSON.parse(vault.backup());conflict.revision++;localStorage.setItem(vault.storageKey,JSON.stringify(conflict));await assert.rejects(vault.save(changed),/autre onglet/);
});
